### PR TITLE
Add support for yarn

### PR DESCRIPTION
**Pull request by gingermusketeer**

### CODE REVIEW

**Comment by gingermusketeer** [comment]
@kruppel Here is the change to support `yarn`. Let me know if you want anything changed!

**Comment by kruppel** [comment]
Not sure why I didn't think of it before, but one of the dilemmas here is that [Yarn doesn't support earlier versions of Node](https://github.com/yarnpkg/yarn/issues/1288).

I haven't quite reached the point where I'm willing to drop support for 0.12; that was actually one of the major draws to authoring this library in the first place. Happy to hear argument for otherwise though.

**Comment by kruppel** [comment]
Haha, I thought this was something entirely different. My bad. This looks sweet. Thanks @gingermusketeer!

**Comment by gingermusketeer** [comment]
@kruppel No problem. Thanks for making this in the first place and for being open to a few tweaks!! :)

**Comment by kruppel** [comment]
@gingermusketeer v1.4.0 published! Thanks again.

**Pull request merged**
